"""
Signal A: LLM-based classifier via Groq (llama-3.3-70b-versatile).

Returns a float in [0.0, 1.0] where values closer to 1.0 indicate
higher confidence that the text is AI-generated.
"""

import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

_client = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY environment variable not set.")
        _client = Groq(api_key=api_key)
    return _client


SYSTEM_PROMPT = """You are an AI-content detection expert. Your sole task is to assess
whether a piece of text was written by a human or generated by an AI language model.

Respond with a single JSON object and nothing else:
{
  "score": <float between 0.0 and 1.0>,
  "reasoning": "<one sentence>"
}

Where score = 1.0 means you are certain the text is AI-generated, and
score = 0.0 means you are certain it is human-written.
Do not include any text outside the JSON object."""

USER_TEMPLATE = """Please assess the following text:

---
{text}
---

Respond only with the JSON object described in your instructions."""


def score_with_groq(text: str) -> float:
    """
    Call Groq with llama-3.3-70b-versatile and return a confidence score
    that the text is AI-generated (0.0 = human, 1.0 = AI).

    Raises on API or parsing errors so the caller can handle them.
    """
    client = _get_client()

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": USER_TEMPLATE.format(text=text)},
        ],
        temperature=0.0,
        max_tokens=128,
        response_format={"type": "json_object"},
    )

    content = response.choices[0].message.content
    import json
    parsed = json.loads(content)
    raw_score = float(parsed["score"])
    # Clamp to [0.0, 1.0] in case the model drifts slightly outside bounds
    return max(0.0, min(1.0, raw_score))
